export const LOAD_POINTS = 'LOAD_POINTS';
export const LOAD_CONTESTANTS = 'LAOD_CONTESTANTS';
export const LOAD_USERS = 'LOAD_USERS';
export const RANK_CONTESTANTS_AND_USERS = 'RANK_CONTESTANTS_AND_USERS';

